<template>
  <div class="cookie-policy">
    <h2>Our cookie policy</h2>
    <h3>What are cookies?</h3>
    <p>A cookie is a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.</p>
    <h3>How do we use cookies?</h3>
    <p>We use cookies to give you a token in exchange for logging in with valid credentials.</p>
    <p>This token is used to authenticate yourself when using the application. 
      This enables us to let our users create their own todo lists, that aren't accessible to other users unless the user explicitly shares them.</p>
  </div>
</template>

<style lang="scss">
  .cookie-policy {
    padding: 60px;
    max-width: 1000px;
    margin: 50px auto;
    background: #222;

    h2 {
      margin-bottom: 30px;
    }

    p {
      margin-bottom: 30px
    }

    &:last-child {
      margin-bottom: 0;
    }
  }
</style>
